version: '3'
services:
  todoback:
    image: todobackend
    restart: always
    ports:
      - 3001:3001
    # ...
    # parâmetros
    # ...
  todofront:
    image: todofrontend
    restart: always
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
    ports:
      - 3000:3000
    # ...
    # parâmetros
    # ...
  todotests:
    image: todotests
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
  # ...