version: '3'
services:
  todofrontend:
    build: ./todo-app/front-end/
    restart: always
    environment:
      - REACT_APP_API_HOST=backend
    depends_on:
      - back-end/
    ports:
      - 3000:3000
    # ...
    # parâmetros
    # ...
  todobackend:
    build: ./todo-app/back-end/
    restart: always
    ports:
      - 3001:3001
    # ...
    # parâmetros
    # ...
  todotests:
    build: ./todo-app/tests/
    depends_on:
      - todobackend
      - todofrontend
    environment:
      - FRONT_HOST=todofrontend
  # ...